services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: 1214
      ORACLE_PDB: XEPDB1
    ports:
      - "1522:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      retries: 10

  fitapp-quarkus:
    image: eduardocoronel/fitapp-quarkus:latest
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      QUARKUS_DATASOURCE_USERNAME: FITAPP
      QUARKUS_DATASOURCE_PASSWORD: 1214

volumes:
  oracle-data: